//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Библиотечной_информационная_система.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.Library_Card = new HashSet<Library_Card>();
            this.LibraryCard_Client = new HashSet<LibraryCard_Client>();
        }
    
        public int id { get; set; }
        public string books { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public int id_location { get; set; }
        public string date_of_publication { get; set; }
        public int id_discipline { get; set; }
        public string Author { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual location location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Library_Card> Library_Card { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LibraryCard_Client> LibraryCard_Client { get; set; }
    }
}
